#
# Copyright 2019 StreamUnlimited
#
# SPDX-License-Identifier:      GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-y += ddr3l_1x4Gb_timing.o ddr3l_2x2Gb_timing.o
else
obj-y += stream195x.o
endif
